apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: source
  name: source
  namespace: b6010768
spec:
  replicas: 1
  selector:
    matchLabels:
      app: source
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: source
    spec:
      containers:
      - image: chanwit/source
        imagePullPolicy: Always
        name: source
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
